name: SonarCloud Analysis
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]

# OU après achèvement des tests ?
# on:
#   workflow_run:
#     workflows: ["Unit Tests"]
#     types:
#       - completed

jobs:
  frontend:
    name: Frontend (Angular) - SonarCloud
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install deps 
        run: npm ci

      - name: Run tests & coverage
        run: npm run test -- --no-watch --browsers=ChromeHeadless --code-coverage

      - name: SonarCloud Scan (frontend)
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          # indique le dossier contenant le sonar-project.properties ou les sources
          projectBaseDir: front
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  backend:
    name: Backend (Spring/Maven) - SonarCloud
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build & tests (Maven) - génère JaCoCo
        working-directory: backend
        run: mvn -B -DskipTests=false clean verify

      - name: Sonar - Maven analysis (backend)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
            -Dsonar.organization=romainchavalle
            -Dsonar.projectKey=romainchavalle_bobapp_backend
